#!/system/bin/sh

chmod 0666 /sys/devices/system/cpu/cpu0/cpufreq/interactive/target_loads
chmod 0666 /sys/devices/system/cpu/cpu1/cpufreq/interactive/target_loads
chmod 0666 /sys/devices/system/cpu/cpu2/cpufreq/interactive/target_loads
chmod 0666 /sys/devices/system/cpu/cpu3/cpufreq/interactive/target_loads
chmod 0666 /sys/devices/system/cpu/cpu4/cpufreq/interactive/target_loads
chmod 0666 /sys/devices/system/cpu/cpu5/cpufreq/interactive/target_loads
chmod 0666 /sys/devices/system/cpu/cpu0/cpufreq/interactive/hispeed_freq
chmod 0666 /sys/devices/system/cpu/cpu1/cpufreq/interactive/hispeed_freq
chmod 0666 /sys/devices/system/cpu/cpu2/cpufreq/interactive/hispeed_freq
chmod 0666 /sys/devices/system/cpu/cpu3/cpufreq/interactive/hispeed_freq
chmod 0666 /sys/devices/system/cpu/cpu4/cpufreq/interactive/hispeed_freq
chmod 0666 /sys/devices/system/cpu/cpu5/cpufreq/interactive/hispeed_freq

echo "1 1382400:60 16128000:80" > /sys/devices/system/cpu/cpu0/cpufreq/interactive/target_loads
echo "1 1382400:60 16128000:80" > /sys/devices/system/cpu/cpu1/cpufreq/interactive/target_loads
echo "1 1382400:60 16128000:80" > /sys/devices/system/cpu/cpu2/cpufreq/interactive/target_loads
echo "1 1382400:60 16128000:80" > /sys/devices/system/cpu/cpu3/cpufreq/interactive/target_loads
echo "1 1382400:80" > /sys/devices/system/cpu/cpu4/cpufreq/interactive/target_loads
echo "1 1382400:80" > /sys/devices/system/cpu/cpu5/cpufreq/interactive/target_loads

echo "1382400" > /sys/devices/system/cpu/cpu0/cpufreq/interactive/hispeed_freq
echo "1382400" > /sys/devices/system/cpu/cpu1/cpufreq/interactive/hispeed_freq
echo "1382400" > /sys/devices/system/cpu/cpu2/cpufreq/interactive/hispeed_freq
echo "1382400" > /sys/devices/system/cpu/cpu3/cpufreq/interactive/hispeed_freq
echo "1382400" > /sys/devices/system/cpu/cpu4/cpufreq/interactive/hispeed_freq
echo "1382400" > /sys/devices/system/cpu/cpu5/cpufreq/interactive/hispeed_freq
